Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myportfolio.urls')),
    path('blog/', include('blog.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import all_blogs, detail, blog_create, blog_update, blog_delete, login_view, logout_view, register, user_list

app_name = 'blog'

urlpatterns = [
	path('login/', login_view, name='login'),
    path('register/', register, name='register'),
    path('logout/', logout_view, name='logout'),
    path('', all_blogs, name = 'all_blogs'),
    path('list/<int:blog_id>', detail, name = 'detail'),
    path('create/', blog_create, name = 'blog_create'),
    path('update/<int:blog_id>', blog_update, name = 'blog_update'),
    path('delete/<int:blog_id>', blog_delete, name = 'blog_delete'),
    path('userlist', user_list, name = 'user_list'),

]

myportfolio/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name = 'home'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField(auto_now_add = True)
    author = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
    	return self.title

myportfolio/models.py
from django.db import models

# Create your models here.
class Portfolio(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='myportfolio/images/')
    url = models.URLField(blank=True)

blog/forms.py
from django.forms import ModelForm
from .models import Blog
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class BlogCreateForm(ModelForm):
	class Meta:
		model = Blog
		fields = ['title', 'description']

class RegisterForm(UserCreationForm):	
	class Meta:
		model = User
		fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2', ]

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Blog
from .forms import BlogCreateForm, RegisterForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage


# Create your views here.
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request, 'blog/login.html',context={"form":form})


def register(request):    
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully')
        return redirect("blog:login")
    else:
        form = RegisterForm()

    context = {'form': form}

    return render(request, 'blog/register.html', context)

@login_required
def logout_view(request):
    logout(request)
    return redirect('blog:login')
    
@login_required
def all_blogs(request):
    blogs_count = Blog.objects.count()
    blogs = Blog.objects.order_by('-date')
    pgn = Paginator(blogs, 3)
    page_nums = request.GET.get('page',1)
    try:
    	page = pgn.page(page_nums)
    except EmptyPage:
    	page = pgn.page(1)
    return render(request, 'blog/all_blog.html', {'blogs': page, 'blogs_count':blogs_count})

@login_required
def detail(request,blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    if request.method == 'GET':
    	author = blog.author == request.user
    	return render(request, 'blog/detail.html', {'blog':blog, 'author':author})

@login_required
def blog_create(request):
	if request.method == 'GET':
		forms = BlogCreateForm()
		return render(request, 'blog/blog_create.html', {'forms': forms})
	else:
		blogcreate = BlogCreateForm(request.POST)
		new_createblog = blogcreate.save(commit = False)
		new_createblog.author = request.user
		new_createblog.save()
		return redirect('blog:all_blogs')

@login_required
def blog_update(request,blog_id):
	blog = get_object_or_404(Blog, pk=blog_id, author = request.user)
	if request.method == 'GET':
		form = BlogCreateForm(instance=blog)
		return render(request, 'blog/blog_update.html', {'blog':blog,'form':form})
	else:
		form = BlogCreateForm(request.POST, instance=blog)
		form.save()
		return redirect('blog:all_blogs')

@login_required
def blog_delete(request, blog_id):
	blog = get_object_or_404(Blog, pk=blog_id, author = request.user)
	form = BlogCreateForm(instance=blog)
	if request.method == 'POST':
		blog.delete()
		return redirect('blog:all_blogs')

	return render(request, 'blog/blog_delete.html', {'form':form})

@login_required
def user_list(request):
	users = User.objects.all()
	if request.method == 'GET':
		if request.GET.get('user'):
			users = users.filter(username__contains=request.GET.get('user'))
		return render(request, 'blog/user.html', {'users': users})

myportfolio/views.py
from django.shortcuts import render
from .models import Portfolio
# Create your views here.

def home(request):
    projects = Portfolio.objects.all()

    return render(request, 'myportfolio/home.html', {'projects': projects})

blog/templates/blog/all_blog.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block content %}
<div class="container">
<br>
<br>
<br>
<br>
<br>
	<a href="{% url 'blog:blog_create' %}">Create Blog</a>
    <h1>Bu mening bloglarim. Ularning soni {{blogs_count}} ta</h1>

    {% for blog in blogs %}
    <a href="{% url 'blog:detail' blog.id %}">
        <h2>{{blog.title}}</h2>
    </a>
    <h5>{{blog.date }}</h5>
    <p>{{blog.description |safe |truncatechars:100}}</p>
    <h3>{{blog.author}}</h3>
    <hr>
  {% endfor %}
  {% if blogs.has_previous %}
    <a href="{% url 'blog:all_blogs' %}?page={{blogs.previous_page_number }}">Orqaga</a>
  {% endif %}

  {% for i in blogs.paginator.page_range %}
    <a href="?page={{i}}">{{i}}</a>
  {% endfor %}

  {% if blogs.has_next %}
    <a href="{% url 'blog:all_blogs' %}?page={{blogs.next_page_number }}">Oldinga</a>
  {% endif %}


</div>
{% endblock %}

blog/templates/blog/blog_create.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block content %}
<h1>Blog Create</h1>
<hr>
<form action="{% url 'blog:blog_create' %}" method="POST">
	{% csrf_token %}
	{{forms.as_p}}
	<button type="submit">Submit</button>
</form>

{% endblock %}

blog/templates/blog/blog_delete.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block content %}
<br>
<br>
<br>
<h1>Blog Delete</h1>
<hr>
<p>Siz Blogni delete qilmoqchimisiz </p>
<a href="{% url 'blog:all_blogs' %}">Orqaga qaytish</a>
<form action="" method="POST">
	{% csrf_token %}
	
	<button type="submit">Delete</button>
</form>

{% endblock %}

blog/templates/blog/blog_update.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block content %}
<h1>Blog Update</h1>
<hr>
<form action="" method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<button type="submit">Submit</button>
</form>

{% endblock %}

blog/templates/blog/detail.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block content %}
<div class="container">
 <br>
 <br>
 <br>
 <br>

    <h1>{{blog.title}}</h1>
    <h2>{{blog.date}}</h2>
    <p>{{blog.description}}</p>
    <h2>{{blog.author}}</h2>
    {% if author %}
    <a href="{% url 'blog:blog_update' blog.id %}">Update</a>
    <a href="{% url 'blog:blog_delete' blog.id %}">Delete</a>
    {% endif %}
</div>

{% endblock %}

blog/templates/blog/login.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block title %} Login  {% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>Login page</h1>
    <hr>  
    <form method="POST" class="from-group">
	{% csrf_token %}
	{{form.as_p}}
	<p>Don't have an accoount? Create one <a href="/blog/register">Register</a></p>
	<button type="submit" class="btn btn-success">Login</button>	
    </form>
</div>
{% endblock %}

blog/templates/blog/register.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h1>
        Register page
    </h1>
    <hr>
        
            <form class="form-group" method="POST">
                {% csrf_token %}

                <div class="form-group">
                    {{ form.first_name.label }}
					{{ form.first_name}}
                </div>

                <div class="form-group">
                    {{ form.last_name.label }}
					{{ form.last_name}}
                </div>

                <div class="form-group">
                    {{ form.username.label }}
					{{ form.username}}
                </div>

                <div class="form-group">
					{{ form.email.label }}
					{{ form.email}}
                </div>

                <div class="form-group">
                    {{ form.password1.label }}
					{{ form.password1}}
                </div>

                <div class="form-group">
                    {{ form.password2.label }}
					{{ form.password2}}
                </div>
                {{form.error}}
                <div>
                	<p>This is Login <a href="/blog/login">login</a></p>
                </div>
                 <div class="form-group">
                    <button class="btn btn-success" type="submit">
                        Register
                    </button>
                </div>
		
                    
                </br>
            </form>
        </hr>
    </hr>
</div>
{% endblock %}

blog/templates/blog/user.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block content %}
<div class="container">
<br>
<br>
<br>
<br>
<br>
<h1>Foydalanuvchilar ruyxati</h1>
	<form action="{% url 'blog:user_list' %}" method="GET">
       <input type="text" name="user">
        <button type="submit">Izlash</button>
    </form>
   <table border="1" width="100%">
    <thead>
        <tr>
            <th>Foydalanuvchi</th>
            <th>So'ngi tashrif</th>
            <th>A'zo bulganligi</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
       <tr>
           <td> {{user.username}}</td>
           <td> {{user.last_login}}</td>
           <td> {{user.date_joined}}</td>
       </tr>
       
        {% endfor %}
    </tbody>
       
   </table>
<br>
<br>
    
</div>
{% endblock %}

myportfolio/templates/myportfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
            <meta content="width=device-width, initial-scale=1.0" name="viewport">
                {% block title %} {% endblock %}
                <link href="{% static 'myportfolio/css/main.css' %}" rel="stylesheet">
                    <link href="{% static 'myportfolio/css/bootstrap.min.css' %}" rel="stylesheet">
                    </link>
                </link>
            </meta>
        </meta>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light text-uppercase fixed-top">
            <div class="container">
                <a class="navbar-brand font-weight-bold" href="#">
                    Projects
                </a>
                <button aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNav" data-toggle="collapse" type="button">
                    <span class="navbar-toggler-icon">
                    </span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link " href="{% url 'home' %}">
                                Home
                            </a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link " href="{% url 'blog:user_list' %}">
                                Foydalanuvchilar
                            </a>
                        </li>
                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link" href="{% url 'blog:all_blogs' %}">
                                Blog
                            </a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                {{request.user}}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:logout' %}">
                                Logout
                            </a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link " href="{% url 'blog:login' %}">
                                Login
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:register' %}">
                                Register
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %} {% endblock %}
        <footer class="bg-dark text-white text-center">
            <div class="container">
                <div class="row py-lg-5">
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">
                            Location
                        </h4>
                        <p class="lead mb-0">
                            2215 John Daniel Drive
                            <br/>
                            Clark, MO 65243
                        </p>
                    </div>
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">
                            Around the Web
                        </h4>
                    </div>
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">
                            About Freelancer
                        </h4>
                        <p class="lead mb-0">
                            Freelance is a free to use, MIT licensed Bootstrap theme created by
                            <br>
                                <a href="http://startbootstrap.com">
                                    Start Bootstrap
                                </a>
                            </br>
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <div class="copyright py-4 text-center text-white bg-secondary">
            <div class="container">
                <small>
                    Copyright © Your Website 2020
                </small>
            </div>
        </div>
        <script src="{% static 'myportfolio/js/jquery.slim.min.js' %}">
        </script>
        <script src="{% static 'myportfolio/js/popover.js' %}">
        </script>
        <script src="{% static 'myportfolio/js/bootstrap.min.js' %}">
        </script>
    </body>
</html>

myportfolio/templates/myportfolio/home.html
{% extends 'myportfolio/base.html' %}
{% load static %}

{% block content %}

<div class="container">
  
  <br>
  <br>
  <br>
  <br>
  <br>
  <h1>Bu mening birinchi dasturim</h1>
  <div class="myImage">
    <img src="{% static 'myportfolio/images/bobur.jpg' %}" alt="">
  </div>
  <h1>Portfolio</h1>
  <hr>
  <div class="row">

    {% for project in projects %}
    <div class="col-4">
      <div class="card">
        <img class="card-img-top" src="{{project.image.url}}" alt="">
        <div class="card-body">
          <h2 class="card-title">{{project.title}}</h2>
          <p class="card-text">{{project.description}}</p>
          <br>
          {% if project.url %}
          <a class="btn btn-primary" href="{{project.url}}">Ishni kurish</a>
          {% endif %}

        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<style>
  .myImage {
    display: block;
    margin: 5px auto;
    text-align: center;

  }
</style>

<br>
<br>
<br>

{% endblock %}